version: 2.1
jobs:
  build-test-push:
    docker:
      - image: ${ECR_ENDPOINT}/prisoner-money/money-to-prisoners:deploy-tools
    environment:
      app: start-page
    working_directory: /tmp/repo
    steps:
      - checkout
      - run:
          name: Inspect tags
          command: |
            echo export tag=${app}.${CIRCLE_BRANCH}.${CIRCLE_SHA1:0:7} > /tmp/mtp-env.sh
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Test code
          command: |
            source /tmp/mtp-env.sh
            pip3 install flake8
            flake8
      - run:
          name: Build docker image
          command: |
            source /tmp/mtp-env.sh
            docker build \
              --pull --force-rm \
              --build-arg APP_GIT_COMMIT=${CIRCLE_SHA1} \
              --build-arg APP_GIT_BRANCH=${CIRCLE_BRANCH} \
              --build-arg APP_BUILD_TAG=${tag} \
              --build-arg APP_BUILD_DATE=$(date +%FT%T%z) \
              --tag ${tag} \
              .
      - run:
          name: Push docker image
          command: |
            source /tmp/mtp-env.sh
            $(aws ecr get-login --region eu-west-1 --no-include-email)
            echo "Pushing ${tag} to ECR"
            docker tag ${tag} ${ECR_ENDPOINT}/prisoner-money/money-to-prisoners:${tag}
            docker push ${ECR_ENDPOINT}/prisoner-money/money-to-prisoners:${tag}
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              echo "Pushing ${app} to ECR (acts as latest)"
              docker tag ${tag} ${ECR_ENDPOINT}/prisoner-money/money-to-prisoners:${app}
              docker push ${ECR_ENDPOINT}/prisoner-money/money-to-prisoners:${app}
            fi
workflows:
  version: 2
  build-test-push:
    jobs:
      - build-test-push
